<a href="https://colab.research.google.com/github/hsuemily/CE888_Hsu-Chi-Rou_1900759/blob/master/Lab%205/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [12]:
df = pd.read_csv("https://raw.githubusercontent.com/hsuemily/CE888_Hsu-Chi-Rou_1900759/master/Lab%205/jester-data-1.csv", delimiter = ",")
df

74  -7.82   8.79  -9.66  -8.16  ...  99.22  -5.63  99.23  99.24  99.25
0      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
1       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
2       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
4      100  -6.17  -3.54   0.44  -8.50  ...  -3.35   0.05  -9.08  -5.05  -3.45
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24977  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24978   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24979   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24980   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24982 rows x 101 columns]

In [0]:
arr = df.copy() 
arr = arr.drop(arr.columns[0], axis=1)

In [37]:
arr = arr.values
print(arr.shape)

(24982, 100)


In [38]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

1810381 (1810381,)


In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])


In [0]:
new_arr, idx = replace(arr, 0.1)

In [41]:
arr[idx[0][0], idx[1][0]]

6.36

In [42]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [43]:
new_arr

array([[ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  ,  8.35, 99.  , ..., 99.  , 99.  , 99.  ],
       ...,
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [ 2.43,  2.67, -3.98, ..., 99.  , 99.  , 99.  ]])

In [44]:
arr

array([[ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  ,  8.35, 99.  , ..., 99.  , 99.  , 99.  ],
       ...,
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [ 2.43,  2.67, -3.98, ..., 99.  , 99.  , 99.  ]])

In [0]:
#Use latent factor modeling to infer the hidden ratings of the users(they are labeled as "99" in the dataset) on the training set

n_latent_factors = 2

user_ratings = new_arr
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [77]:
user_ratings.shape[1]

100

In [57]:
latent_item_features

array([[0.845, 0.599],
       [0.627, 0.138],
       [0.566, 0.25 ],
       [0.525, 0.619],
       [0.237, 0.271],
       [0.415, 0.28 ],
       [0.358, 0.242],
       [0.829, 0.937],
       [0.266, 0.564],
       [0.395, 0.389],
       [0.975, 0.993],
       [0.415, 0.877],
       [0.037, 0.517],
       [0.012, 0.789],
       [0.23 , 0.539],
       [0.221, 0.356],
       [0.428, 0.886],
       [0.704, 0.579],
       [0.613, 0.422],
       [0.673, 0.871],
       [0.845, 0.18 ],
       [0.947, 0.863],
       [0.506, 0.24 ],
       [0.466, 0.006],
       [0.461, 0.634],
       [0.134, 0.386],
       [0.604, 0.378],
       [0.028, 0.837],
       [0.536, 0.941],
       [0.133, 0.608],
       [0.576, 0.351],
       [0.74 , 0.433],
       [0.136, 0.546],
       [0.181, 0.764],
       [0.907, 0.026],
       [0.994, 0.269],
       [0.166, 0.135],
       [0.015, 0.452],
       [0.302, 0.516],
       [0.965, 0.027],
       [0.443, 0.033],
       [0.177, 0.135],
       [0.233, 0.27 ],
       [0.0

In [67]:
latent_item_features.shape[0]

100

In [58]:
latent_user_preferences

array([[0.156, 0.692],
       [0.25 , 0.542],
       [0.041, 0.799],
       ...,
       [0.942, 0.35 ],
       [0.395, 0.504],
       [0.265, 0.981]])

In [65]:
latent_user_preferences.shape[0]

24982

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=1000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if (rating!=99):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 1) == 0:
            print(mse)

In [90]:
sgd(50)  # Note how the MSE decreases with the number of iterations

17.120274901868424
17.116030220023166
17.112203354151497
17.108727668096805
17.10557673638592
17.10272147747406
17.10013349511251
17.097786730897774
17.095657713154846
17.0937253958753
17.091970915031826
17.090377349276547
17.08892950415936
17.08761372150346
17.086417711612924
17.085330405456705
17.084341824218267
17.083442963959097
17.082625693472945
17.081882663682425
17.08120722716045
17.080593366550804
17.080035630824987
17.079529078451284
17.079069226669894
17.07865200616988
17.078273720551486
17.077931010032746
17.077620818925404
17.077340366461666
17.077087120603547
17.076858774509336
17.076653225369675
17.07646855535946
17.076303014479763
17.07615500509034
17.07602306795564
17.075905869646412
17.075802191157095
17.075710917614195
17.075631028964608
17.075561591544567
17.07550175044105
17.0754507225664


KeyboardInterrupt: ignored

In [94]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[ 3.083,  3.256,  3.905, ...,  2.58 ,  4.092,  2.808],
       [ 6.948,  7.229,  7.543, ...,  7.356,  7.369,  8.33 ],
       [ 1.551,  1.572,  1.2  , ...,  2.234,  0.933,  2.629],
       ...,
       [-1.074, -1.149, -1.534, ..., -0.685, -1.682, -0.701],
       [-1.169, -1.261, -1.789, ..., -0.6  , -2.006, -0.574],
       [ 2.765,  2.833,  2.498, ...,  3.544,  2.19 ,  4.117]])

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
# comparison_data.columns = new_arr.columns

In [96]:
comparison_data
# For each data point, the number on the left is the original value from the dataset, the number on the right is the prediction

0  ...                           99
0       (4.08, 3.0830035037543997)  ...   (1.07, 2.8078928533580534)
1        (99.0, 6.948280610682404)  ...    (99.0, 8.330491177031327)
2        (99.0, 1.550940222363695)  ...    (99.0, 2.628729399422726)
3         (8.5, 3.096652071465313)  ...    (1.6, 4.4759806666177315)
4      (-6.17, -4.697725500054959)  ...  (-3.45, -5.026924556587874)
...                            ...  ...                          ...
24977   (0.44, 2.2851854874490183)  ...   (7.43, 3.8184680509395252)
24978   (9.13, 2.3562976933057467)  ...   (8.45, 1.3856332659767814)
24979  (99.0, -1.0738759914770715)  ...   (99.0, -0.700709295145384)
24980  (99.0, -1.1689985372862925)  ...  (99.0, -0.5736960767259336)
24981   (2.43, 2.7647908107762067)  ...    (99.0, 4.116660090996267)

[24982 rows x 100 columns]

In [0]:
# not complete~~

In [0]:
# Calculate the performance (e.g., MSE) of the algorithm on the validation dataset


In [0]:
# Repeat the two points above changing hyper-parameters (i.e., learning rate, number of iterations of SVD, 
# number of latent factors, etc.) as needed to get good results (you can create multiple validation sets 
# if you want, and run a bootstrap!)

In [0]:
# Once you're happy, make predictions for the test dataset

In [0]:
# (If you have time) Use pandas to find the best- and the worst-rated jokes